### ISSUE TITLE
ASP.net Core no files

### ISSUE THREAD

**Issue by LorenDorez** [tiesont/Font.Awesome.Packages#2]
I just started a new ASP.net core project in VS2017 and when i add this nuget package i expected the files to go to wwwroot/lib but they dont show up. Am i missing something?

**Comment by tiesont** [comment]
These packages are built for the ASP.NET templates targeting the full framework. So, no, you're not missing anything, the files just aren't going when you are probably expecting.

We don't use .NET Core or .NET Standard where I work, and I haven't put much time into getting familiar with either on my own time, so not sure when/if I'll create versions of these packages that are compatible with the template you're using. I'll add it to my to-do list, though.

**Comment by tiesont** [comment]
@LorenDorez If you're still interested (I know, it's been awhile), I think I've figured out how to set up a package to work with ASP.NET Core's default layout. I don't really want to change the existing packages, though, so I'm going to create a new package, FontAwesome.AspDotNetCore - it will drop pretty much everything you see in the manual download into a folder at `wwwroot/lib/fontawesome`. I'll mention this issue when pushing the package to Github.

**Comment by tiesont** [comment]
Closed. New package is available here: https://www.nuget.org/packages/Font.Awesome.AspDotNetCore/
