### ISSUE TITLE
NuGet package 5.14 Missing files

### ISSUE THREAD

**Issue by dammitjanet** [tiesont/Font.Awesome.Packages#4]
"webfonts" directory and content are missing, 5.13 is fine

**Comment by tiesont** [comment]
Need to be more specific - there are three different NuGet packages.

**Comment by tiesont** [comment]
Fixed in https://github.com/tiesont/Font.Awesome.Packages/commit/2fc9e820b89add86ad5d46ed949295746165f15e. Closing.
