### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Devnsyde** [tiesont/Font.Awesome.Packages#5]
The webfonts directory is missing for the @font-face in fontawesome-all.css and is throwing an error in the developer console, can you add the fonts?

**Comment by Devnsyde** [comment]
Sorry found the fonts in the root directory and its called webfonts, explains why it works fine in debug but not when I release, just need to add to bundles.

**Comment by tiesont** [comment]
Yeah, sorry, I just copy the directory as-is when creating the NuGet package. Probably more effort than it's worth, but it is possible to add either a rewrite rule in your web.config or a custom route mapping that would route requests from `/fonts` to `/webfonts` (assuming you didn't have anything else in the fonts directory).

**Comment by Devnsyde** [comment]
I actually got it all figured out, I would have deleted this issue if I could but didn't see a way so I just closed it. Sorry I bothered you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
